version: "3.9"

services:
  frontend:
    container_name: getinvolved-frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.getinvolvd.com
    ports:
      - "127.0.0.1:3000:80"
    restart: unless-stopped

  backend:
    container_name: getinvolved-backend
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped